import "../style/global.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
// import { Providers } from "./Providers";
export const metadata = {
  title: "Movie Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="w-full p-4 min-h-screen dark:bg-gray-800 text-black dark:text-white">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
